spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  ${ISSUER_URI:http://localhost:8081}
          jwk-set-uri: ${JWK_URI:http://localhost:8081/oauth2/jwks}
      #authorization-server:
        #issuer: ${ISSUER_URI:http://localhost:8081}  # Tambahkan ini jika menggunakan Spring Authorization Server
          # only needed for RS256-based JWTs

server:
  port: 8081

jwt:
  secret: my-super-secure-secret-key-which-is-long-enough-123456
  expiration: 86400000 # in milliseconds (1 day)

# Optional: Logging level (for easier debugging)
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# Spring Security Configuration (if using method-level security or role-based)


# Custom authorization-related properties (you can reference these in code)
auth:
  roles:
    - USER
    - ADMIN
  token:
    prefix: "Bearer "
    header: "Authorization"
