version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-net

  jdih-service:
    build:
      context: ./jdih-service
    container_name: jdih-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH_JWKS_URI=http://auth-service:8081/oauth2/jwks
    depends_on:
      - auth-service
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
