server:
  port: 8082

spring:
  application:
    name: jdih-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://localhost:8081/oauth2/jwks}


