spring:
  application:
    name: auth-service

server:
  port: 8081

jwt:
  secret: my-super-secure-secret-key-which-is-long-enough-123456
  expiration: 86400000 # in milliseconds (1 day)

# Optional: Logging level (for easier debugging)
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# Spring Security Configuration (if using method-level security or role-based)
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/oauth2/jwks
        # only needed for RS256-based JWTs

# Custom authorization-related properties (you can reference these in code)
auth:
  roles:
    - USER
    - ADMIN
  token:
    prefix: "Bearer "
    header: "Authorization"
